/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario_menu;

import inicio_sesion.inicio_sesion_jframe;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import usuario_pkg.usuario_registrado;

/**
 *
 * @author royer
 */
public class agregar_jframe extends javax.swing.JFrame {

    /**
     * Creates new form agregar_jframe
     */
    
    private usuario_registrado usuario = null;
    // bandera para saber si el usuario esta accediendo desde el menu o desde el login
    // FALSE: registrar -> menu, TRUE: registrar -> login
    public boolean esMenu;
    
    public agregar_jframe() {
        initComponents();
    }
    
    public agregar_jframe(boolean esMenu) {
        this.esMenu = esMenu;
        initComponents();
    }
    
    public agregar_jframe(usuario_registrado usuario, boolean esMenu) {
        initComponents();
        this.usuario = usuario;
        this.esMenu = esMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrar_btn = new javax.swing.JButton();
        cancelar_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contrasena_txt = new javax.swing.JTextField();
        nombre_txt = new javax.swing.JTextField();
        ID_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrar_btn.setText("registrar");
        registrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_btnActionPerformed(evt);
            }
        });

        cancelar_btn.setText("cancelar");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("contraseña");

        jLabel5.setText("nombre");

        jLabel6.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(registrar_btn)
                        .addGap(160, 160, 160)
                        .addComponent(cancelar_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contrasena_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(ID_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombre_txt))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(contrasena_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_btn)
                    .addComponent(cancelar_btn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_btnActionPerformed
        // TODO add your handling code here:
        // boton para registrar 
        Connection conexion = null;
        PreparedStatement sentencia_preparada = null;
        ResultSet query = null;
        try{
            // se encarga de verificar si no se dejan campos en vacio
            if(!"".equals(this.nombre_txt.getText()) && !"".equals(this.ID_txt.getText()) && !"".equals(this.contrasena_txt.getText())){
                conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/usuarios","root", "");
                // query parametrizado, mejor protegido contra inyeccion SQL
                String queryInsertSQL = "INSERT INTO usuario (nombre, ID, contrasena) VALUES(?, ?, ?);";
                sentencia_preparada = conexion.prepareStatement(queryInsertSQL);
                // orden de sentencias/query desde el string de conexion (1 = nombre, ID = 2, 3= contraseña)
                // sets the String value to the given parameter index.
                sentencia_preparada.setString(1, this.nombre_txt.getText());
                sentencia_preparada.setString(2, this.ID_txt.getText());
                sentencia_preparada.setString(3, this.contrasena_txt.getText());
                // executes the query. It is used for create, drop, insert, update, delete etc.
                sentencia_preparada.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "usuario agregado exitosamente");
                System.out.println("usuario agregado exitosamente");
                System.out.println();
                this.cancelar_btn.setText("salir");
                
            }else{
                System.out.println("favor de introducir valores en todos los campos de texto");
                System.out.println();
                JOptionPane.showMessageDialog(rootPane, "favor de introducir valores en todos los campos de texto");
            }
            
            
        }catch(SQLException ex){
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
            System.out.println();
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            System.out.println(e);
            e.printStackTrace();
        }
        finally{
            if (conexion != null){
                try{
                    query.close();
                    sentencia_preparada.close();
                    conexion.close();
                }catch (SQLException e){
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_registrar_btnActionPerformed

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
        // TODO add your handling code here:
        // boton para cancelar la solicitud de registrar o regresar al menu
        // si usuario tiene valores, se pasa el objeto usuario registrado al menu
        // bandera para saber si el usuario esta accediendo desde el menu o desde el login
        // FALSE: registrar -> menu, TRUE: registrar -> login
        if (esMenu == true){
            inicio_sesion_jframe login = new inicio_sesion_jframe();
            login.setVisible(true);
            dispose();
        }else{
            menu menu = new menu(usuario);
            menu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_cancelar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_txt;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JTextField contrasena_txt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JButton registrar_btn;
    // End of variables declaration//GEN-END:variables
}
