/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario_menu;
import javax.swing.JOptionPane;
import usuario_pkg.*;
/**
 *
 * @author royer
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    // TODO: encontrar forma de pasar valores de objeto usuario sin utilizar
    // una variable global
    private usuario_registrado usuario = null;
    
    public menu() {
        initComponents();
    }
    
    public menu(usuario_registrado usuario){
        initComponents();
        this.usuario = usuario;
        this.nombre_lbl.setText(usuario.getNombre());
        this.ID_lbl.setText(usuario.getID());
        this.contra_lbl.setText(usuario.getContrasena());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar_btn = new javax.swing.JButton();
        modificar_lbl = new javax.swing.JButton();
        eliminar_lbl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombre_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID_lbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contra_lbl = new javax.swing.JLabel();
        salir_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregar_btn.setText("agregar");
        agregar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_btnActionPerformed(evt);
            }
        });

        modificar_lbl.setText("modificar");
        modificar_lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_lblActionPerformed(evt);
            }
        });

        eliminar_lbl.setText("eliminar");
        eliminar_lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_lblActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre");

        nombre_lbl.setText("jLabel2");
        nombre_lbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nombre_lblPropertyChange(evt);
            }
        });

        jLabel3.setText("ID");

        ID_lbl.setText("jLabel4");

        jLabel5.setText("contraseña");

        contra_lbl.setText("jLabel6");

        salir_btn.setText("salir");
        salir_btn.setToolTipText("");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombre_lbl)
                                .addComponent(ID_lbl)
                                .addComponent(contra_lbl)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(agregar_btn)
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(salir_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modificar_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminar_lbl)
                        .addGap(144, 144, 144)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID_lbl)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contra_lbl))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_btn)
                    .addComponent(modificar_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar_lbl)
                    .addComponent(salir_btn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_btnActionPerformed
        // TODO add your handling code here:
        // boton para agregar nuevos usuarios
        // bandera para saber si el usuario esta accediendo desde el menu o desde el login
        // FALSE: registrar -> menu, TRUE: registrar -> login
        agregar_jframe modificar = new agregar_jframe(usuario, false);
        modificar.setVisible(true);
        dispose();
    }//GEN-LAST:event_agregar_btnActionPerformed

    private void nombre_lblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nombre_lblPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_lblPropertyChange

    private void modificar_lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_lblActionPerformed
        // TODO add your handling code here:
        // boton para modificar valores de usuario
        modificar_jframe modificar = new modificar_jframe(usuario);
        modificar.setVisible(true);
        dispose();
    }//GEN-LAST:event_modificar_lblActionPerformed

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        // http://franvarvil.blogspot.com/2011/11/ventanas-de-confirmacion-en-joptionpane.html
        // https://stackoverflow.com/questions/8396870/joptionpane-yes-or-no-window
        // valores de yes_option & no_option https://docs.oracle.com/javase/7/docs/api/constant-values.html#javax.swing.JOptionPane.YES_OPTION
        // boton para cerrar la app
        // JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        // TODO: encontrar forma de regresar a la aplicacion cuando se haga click en NO
        JOptionPane.showConfirmDialog(null, "¿desea salir de la app?", "salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (JOptionPane.YES_OPTION == 0){
            System.exit(0);
        } else if(JOptionPane.NO_OPTION == 1){
            
        }
        
    }//GEN-LAST:event_salir_btnActionPerformed

    private void eliminar_lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_lblActionPerformed
        // TODO add your handling code here:
        eliminar_jframe e = new eliminar_jframe(usuario);
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_eliminar_lblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_lbl;
    private javax.swing.JButton agregar_btn;
    private javax.swing.JLabel contra_lbl;
    private javax.swing.JButton eliminar_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton modificar_lbl;
    public javax.swing.JLabel nombre_lbl;
    private javax.swing.JButton salir_btn;
    // End of variables declaration//GEN-END:variables
}
